### ISSUE TITLE
你好，能否将离线声音里的两种加到在线里面去？

### ISSUE THREAD

**Issue by perfect-network** [Baidu-AIP/speech-tts-cors#2]
不知道是个人习惯，还是听力问题。

我总感觉在最快速度听语音合成的声音时，只有离线时的女生最是清晰可辨。听着毫无压力。

但是，如果是在线模式的话，声音可辨识度就降低了。我就需要速起耳朵来听了。。。。很难受。

所以，贵公司能否将此离线模式也加到在线模式离线去？

我的意思就是。

per	选填	发音人选择, 0为普通女声，1为普通男生，3为情感合成-度逍遥，4为情感合成-度丫丫，默认为普通女声
在这里增加两个选项，例如4，5     4代表离线女声，5代表离线男音。

不然的话会影响一部分用户的使用。。。

如贵开发组的大佬看到了，还请回个邮件到：admin@skyqq.cc

感激不尽。

**Comment by meteorasd555** [comment]
restful api是没有离线男声和女声女声的

**Comment by perfect-network** [comment]
> restful api是没有离线男声和女声女声的
那能否不要在线时强制使用restful api的。。。。听着听不清楚啊   模糊。。。。

**Comment by meteorasd555** [comment]
restful api就是在线的，在线就是restful api

**Comment by perfect-network** [comment]
> restful api就是在线的，在线就是restful api

啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊，老哥 我只想在无论任何网络都使用离线的女神就好
