### ISSUE TITLE
语音识别选择英文,1737,为什么句子之间不分开,也没有标点符号?

### ISSUE THREAD

**Issue by sunyiwei24601** [Baidu-AIP/speech-tts-cors#3]
![image](https://user-images.githubusercontent.com/32425755/53299303-284c6300-3873-11e9-90cb-b59976fcbb30.png)
![image](https://user-images.githubusercontent.com/32425755/53299308-38644280-3873-11e9-8327-180989ced197.png)

**Comment by meteorasd555** [comment]
接口本身的问题请加入百度AI开发平台（http://ai.baidu.com/）底部qq群或在百度云控制台发工单咨询
