### ISSUE TITLE
bug: the tts bash.sh restful api , forgot the AUE for request url.

### ISSUE THREAD

**Issue by wangpengli** [Baidu-AIP/speech-tts-cors#5]
tts_url="http://tsn.baidu.com/text2audio?lan=zh&ctp=1&cuid=123456&tok=$token&per=$SPEAKER&spd=$SPEED&pit=$PITCH&vol=$VOLUME&tex=$TEXT"

in this url ,not include the AUE for define the audio format ,so if use the default url , always get mp3 format which should the default format.

**Comment by meteorasd555** [comment]
I have fixed it
